from paida.paida_core.PAbsorber import *
class IConstants:

	AIDA_VERSION = '3.2'
	AIDA_VERSION_MAJOR = 3
	AIDA_VERSION_MINOR = 2
	AIDA_VERSION_BUGFIX = 1

	PAIDA_VERSION = '2.10.1'
	PAIDA_VERSION_MAJOR = 2
	PAIDA_VERSION_MINOR = 10
	PAIDA_VERSION_BUGFIX = 1
